### PR TITLE
Integration tests

### PR DESCRIPTION
**Pull request by sboorlagadda**
These tests expect $GEODE_HOME is set to an installed GEODE location or skipped otherwise.

### CODE REVIEW

**Comment by jdeppe-pivotal** [comment]
Thanks Sai. I'd like to keep the tests consistent using `ginkgo`. Could you convert these?

**Comment by sboorlagadda** [comment]
Sure, I like `ginkgo`. I will convert and update the PR.

**Comment by sboorlagadda** [comment]
@jdeppe-pivotal Let me know if these are good. There is an issue that still needs to be looked into that `GetAll`, which is not returning `failures`.

**Comment by jdeppe-pivotal** [comment]
This is great! Thanks

**Pull request merged**
